// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDpHR2oNY4aIL8zcZsp9piCe2379SAPbY',
    appId: '1:568210005885:web:1adc71f44e962ee9e6b614',
    messagingSenderId: '568210005885',
    projectId: 'assignment4-30736',
    authDomain: 'assignment4-30736.firebaseapp.com',
    storageBucket: 'assignment4-30736.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqsdEH9AEhYmJWg_yQ05vifRD9id18Cz8',
    appId: '1:568210005885:android:782e5faf91893a3ae6b614',
    messagingSenderId: '568210005885',
    projectId: 'assignment4-30736',
    storageBucket: 'assignment4-30736.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjftyVVOeFgtCidEIWvR_urQuReFrT730',
    appId: '1:568210005885:ios:b70f706136a615cde6b614',
    messagingSenderId: '568210005885',
    projectId: 'assignment4-30736',
    storageBucket: 'assignment4-30736.appspot.com',
    iosClientId: '568210005885-76fb3j7kj7lidu3irn2qtri8tcqsslao.apps.googleusercontent.com',
    iosBundleId: 'pk.nabeel.crashcourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjftyVVOeFgtCidEIWvR_urQuReFrT730',
    appId: '1:568210005885:ios:b70f706136a615cde6b614',
    messagingSenderId: '568210005885',
    projectId: 'assignment4-30736',
    storageBucket: 'assignment4-30736.appspot.com',
    iosClientId: '568210005885-76fb3j7kj7lidu3irn2qtri8tcqsslao.apps.googleusercontent.com',
    iosBundleId: 'pk.nabeel.crashcourse',
  );
}
